# Generated by Django 3.1.7 on 2021-03-06 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movietype',
            old_name='typedescription',
            new_name='moviedescription',
        ),
        migrations.RenameField(
            model_name='movietype',
            old_name='typename',
            new_name='moviename',
        ),
    ]
