# Generated by Django 3.1.7 on 2021-03-08 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0003_auto_20210307_1823'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movietype',
            old_name='typedescription',
            new_name='moviedescription',
        ),
    ]
